adapter_path: artifacts/checkpoint-final
attn_impl: sdpa
config_path: artifacts/config/config.yaml
dataset_len: 2000
debug: false
do_eval: false
epochs: 1
eval_batch_size: 4
eval_steps: 20
eval_strategy: steps
grad_acc_steps: 8
learning_rate: 0.0002
load_adapter: false
log_level: debug
logging_steps: 10
lora_alpha: 64
lora_bias: none
lora_dropout: 0.05
lora_r: 64
lora_target_modules:
- up_proj
- down_proj
- gate_proj
- o_proj
- v_proj
- k_proj
- q_proj
lora_task_type: CAUSAL_LM
lr_scheduler: linear
max_seq_len: 2048
model_id: meta-llama/Llama-3.2-3B-Instruct
optim: paged_adamw_8bit
output_dir: artifacts/checkpoint-final
save_steps: 100
train_batch_size: 2
use_cache: false
use_dora: false
use_rslora: false
val_size: 0.02
wandb: true
warmup_ratio: 0.1
weight_decay: 0.01
